### ISSUE TITLE
Lack of Documentation for Sockets

### ISSUE THREAD

**Issue by mlangens** [Raathigesh/Hermes#57]
Hello,

I found a link that no longer works. https://github.com/Raathigesh/Atmo/blob/master/docs/SocketEndpoint.md

**Comment by Raathigesh** [comment]
Sockets are no longer supported in the electron app version. You have to use the CLI version to use sockets. You can find the previous docs over here. https://github.com/Raathigesh/atmo/tree/classic/docs
